eureka:
  context-path: /my-eureka-server
  single-instance:
    host: localhost
    port: 9099
  client:
    service-url: 
      defaultZone: http://${eureka.single-instance.host}:${eureka.single-instance.port}${eureka.context-path}/eureka
  instance:
    statusPageUrlPath: ${server.servlet.context-path}${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${server.servlet.context-path}${management.endpoints.web.base-path}/health
    instanceId: ${spring.application.name}:${server.port}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: random-microservice

server:
  servlet:
    context-path: /random-service
  port: 0

info:
  app-name: ${spring.application.name}
  
management:
  endpoint:
    # enable health, info and shutdow actuators
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    shutdown:
      enabled: true
  endpoints:
    web:
                 # set default actuator base-path
      base-path: /actuator
      exposure:
                 # expouse all enabled actuators (*)
        include: '*'
    

logging:
  level:
    #org.apache.http: DEBUG
    mx.com.truper.springboot.practica23.ribbon.usersmicroservice.logging: OFF
    org.springframework.cloud: OFF
    com.netflix.loadbalancer: OFF
#mvn spring-boot:run -Dspring-boot.run.profiles=client-in-single-eureka -Dspring-boot.run.arguments=--server.port=55991
